phraseapp:
  access_token: 072a987f6f778868fa27a80a8f431630847bdcb2c652be5c86625ef40f182c04
  project_id: b5bddf0e6f96f00570510eb5d494d49c
  push:
    sources:
    - file: ./final-strings-<locale_code>.xml
      params:
        file_format: xml
  pull:
    targets:
    - file: ../product_mobile_ios_rider/CabifyRider/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        format_options:
          convert_placeholder: true
