phraseapp:
  access_token: 04d7e31243ecb7d75581d4a440bd71c0eb6d8bb78b302286a63d08fb423f633c
  project_id: c527bb48a658d0b310a48b24901b72d4
  push:
    sources:
    - file: ./strings-<locale_code>.xml
      params:
        file_format: xml
  pull:
    targets:
    - file: ../product_mobile_ios_rider/CabifyRider/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        format_options:
          convert_placeholder: true
